Fix runners attributes with resource pack script
eclipse-cbi/ci-admin pull request #26
Opened 2023-11-29 15:25 UTC by heurtematte

2023-11-29 15:31 UTC, heurtematte commented
NOTE: not perfect but I have added a FIXME comment when the script add a new resourcepack attribut to config.jsonnet but displayname is not ended by a coma. 

I tried with jsonnet cmd line but for config.jsonnet that includes custom template `currentCloud.templates["centos-8"], compilation fails.
We need to find a clean solution for template inclusion in projects config files.

2023-11-30 16:16 UTC, fredg02 commented on jenkins/add_resource_pack.sh
> +  printf "ERROR: Number of dedicated runners must be given.\n"
Please replace "dedicated runners" with "GitHub large runners" everywhere.

2023-11-30 16:17 UTC, fredg02 commented on jenkins/add_resource_pack.sh
> +    #FIXME does not work if diplayName is not ended with a comma
This should work:
```
#Adds missing comma if required
if [[ $(grep "displayName" "${config_file}" | grep -o '.$') != "," ]]; then
  sed -i -r "s/(displayName.*$)/\1,/g" "${config_file}"
fi
```

2024-02-09 20:02 UTC, fredg02 requested changes
See my comment above.

2024-02-12 10:43 UTC, heurtematte commented
done!

2024-02-13 10:18 UTC, fredg02 approved these changes

2024-02-13 10:18 UTC, merged